"""main.py - Command line entry point.  Example:  python main.py --households 15 --days 7"""
from __future__ import annotations

import argparse
import time

import pandas as pd

from config import Config
from data_generator import generate_profiles, load_profiles_csv, save_profiles_csv
from experiments import run_experiments, summarize, comparison_table, save_outputs, robustness_study
from visualization import make_all_plots


def parse_args():
    p = argparse.ArgumentParser(description="Decentralised multi-agent energy trading (SA + Double Auction)")
    p.add_argument("--households", type=int, default=15, help="number of households (10-20 recommended)")
    p.add_argument("--days", type=int, default=7)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--sa-iters", type=int, default=None, help="max SA iterations per replanning")
    p.add_argument("--csv", type=str, default=None, help="optional CSV: household_id,hour,solar_generation,demand")
    p.add_argument("--out", type=str, default="results")
    p.add_argument("--plots", type=str, default="plots")
    p.add_argument("--robustness", type=int, default=0, help="also repeat with N extra seeds (3-day runs)")
    p.add_argument("--no-plots", action="store_true")
    return p.parse_args()


def main():
    a = parse_args()
    kw = dict(n_households=a.households, n_days=a.days, seed=a.seed)
    if a.sa_iters:
        kw["sa_max_iter"] = a.sa_iters
    cfg = Config(**kw)
    profiles = load_profiles_csv(a.csv, cfg) if a.csv else generate_profiles(cfg)
    if a.csv:
        cfg = Config(**{**kw, "n_households": len(profiles)})
    save_profiles_csv(profiles, "data/sample_profiles.csv")

    print(f"Households: {len(profiles)} | days: {cfg.n_days} | seed: {cfg.seed} | SA max iters: {cfg.sa_max_iter}")
    print("Household types:", {p.household_id: ",".join(p.tags) for p in profiles})
    t0 = time.time()
    results = run_experiments(cfg, profiles, verbose=True)
    summary = summarize(results)
    table = comparison_table(summary)
    save_outputs(results, summary, table, a.out)
    pd.set_option("display.width", 200); pd.set_option("display.max_columns", 20)
    print("\n=== COMPARISON TABLE (all numbers generated by this run) ===")
    print(table.to_string(index=False))
    print(f"\nPrice of Anarchy (project metric, selfish cost / cooperative cost): {summary['price_of_anarchy']:.4f}")
    print(f"PoA on SOC-adjusted cost: {summary['price_of_anarchy_soc_adjusted']:.4f}")
    for sc, r in results.items():
        print(f"SA stats [{sc}]: {r.sa_stats}")
    if not a.no_plots:
        files = make_all_plots(results, a.plots)
        print(f"\nSaved {len(files)} plots to '{a.plots}/'")
    if a.robustness:
        df = robustness_study(Config(**{**cfg.to_dict(), "n_days": 3}), range(100, 100 + a.robustness))
        agg = df.groupby("scenario")[["total_cost", "peak", "grid_dep", "p2p", "fairness"]].agg(["mean", "std"]).round(3)
        agg.to_csv(f"{a.out}/robustness_summary.csv"); df.to_csv(f"{a.out}/robustness_runs.csv", index=False)
        print("\n=== ROBUSTNESS (mean/std over seeds, 3-day runs) ===\n", agg.to_string())
        print("PoA per seed:", df.groupby("seed")["poa"].first().round(3).to_dict())
    print(f"\nTotal wall time: {time.time() - t0:.1f}s. Results in '{a.out}/'.")


if __name__ == "__main__":
    main()
